### ISSUE TITLE
kfp.Client 연결 관련 질문드립니다. 

### ISSUE THREAD

**Issue by kim-sardine** [byeongjokim/MLOps-Example#1]
안녕하세요~ Kubeflow 블로그 글 읽어보다가 궁금한점이 생겨 질문드립니다.

https://github.com/byeongjokim/MLOps-Example/blob/650ecd8620cfda763537538e7cb01a6c5e7f4dd8/.github/workflows/cd.yml#L28

위와 같이 github actions 사용해서 파이프라인을 실행하고 계시는데요,
github actions 에서 kubernetes Cluster 로 어떻게 바로 연결이 가능한가요?

보통 `kfp.Client` 를 사용해서 host 로 접근하려고하면 client_id 또는 cookies 통해서 인증을해주는 절차가 필요한데
아래 코드에서는 host 만으로도 돌아가는것으로 보여서 궁금해서 질문드립니다

https://github.com/byeongjokim/MLOps-Example/blob/650ecd8620cfda763537538e7cb01a6c5e7f4dd8/kubeflow_pipeline/pipeline.py#L73-L83

(블로그 글 잘 읽었습니다ㅎㅎ 마지막 Slack 편도 기다리고있습니다)

**Comment by byeongjokim** [comment]
우선 kubeflow가 설치되어 있는 곳은 제 개인 PC입니다. 또한 간단한 실습을 위해 아무런 인증 절차를 설정하지 않았습니다. 따라서 아무 인증 없이 host로만 접근이 가능한 것입니다..ㅎㅎ

google cloud에서 사용 중 이시면, 따로 인증이 필요할 것입니다. 이에 관한 내용은 [kubeflow-authentication](https://www.kubeflow.org/docs/distributions/gke/pipelines/authentication-sdk/) 에 있는 것 같네요!!

블로그에 대해 말씀드리기는 글쏨씨 때문에.. 많이 부끄러운데.... github.io 에서 tistory로 블로그를 옮겼습니다. slack에 관한 내용도 [tistory](http://byeongjo-kim.tistory.com/) 에서 확인 가능합니다......!!

**Comment by kim-sardine** [comment]
github actions 에서 로컬 k8s 로 request 를 날릴 수 있나요?

**Comment by kim-sardine** [comment]
아하 이해했습니다ㅎㅎ 로컬에 서버를 구축했다고 보면되겠네요
답변 감사합니다~!
